Ajout fonctionnalité Crous dans Helper
MAXOUXAX/mULti4J pull request #2
Opened 2023-02-03 17:20 UTC by NicoRiri

Crous - Test Crous - Modification du Helper

2023-02-04 14:44 UTC, MAXOUXAX requested changes
Hey!
Just looked at your Pull request and commented on a few lines - it would be great if you could make all those changes before I merge this into the project!

Thanks :)

2023-02-04 14:44 UTC, MAXOUXAX commented on src/main/java/me/maxouxax/multi4j/crous/RestoCrous.java
> +    String MenuRu;
Please follow Java variables naming convention.

```suggestion
    String nomRu;
    String imageRu;
    String dateRu;
    String menuRu;
```

2023-02-04 14:44 UTC, MAXOUXAX commented on src/main/java/me/maxouxax/multi4j/crous/RestoCrous.java
> +        MenuRu = menuRu;
```suggestion
        this.nomRu = nomRu;
        this.imageRu = imageRu;
        this.dateRu = dateRu;
        this.menuRu = menuRu;
```

2023-02-04 14:44 UTC, MAXOUXAX commented on src/main/java/me/maxouxax/multi4j/crous/RestoCrous.java
> +    }
```suggestion
    public String getNomRu() {
        return this.nomRu;
    }

    public String getImageRu() {
        return this.imageRu;
    }

    public String getDateRu() {
        return this.dateRu;
    }

    public String getMenuRu() {
        return this.menuRu;
    }
```

2023-02-04 14:44 UTC, MAXOUXAX commented on src/test/java/me/maxouxax/multi4j/CrousTest.java
> +}
Please uncomment this test and actually complete it

2023-02-04 14:44 UTC, MAXOUXAX commented on src/test/java/me/maxouxax/multi4j/CrousTest.java
> +}
Please uncomment this test and actually complete it

2023-02-04 14:44 UTC, MAXOUXAX commented on src/main/java/me/maxouxax/multi4j/MultiHelper.java
> +        return (new RestoCrous(titleRu, imageRu, dateRu, menuRu));
It would be nice if you could rename those variables to what they are actually used for - giving weird names like that isn't great :(

2023-02-12 22:06 UTC, NicoRiri commented
Tout corrigé*

2023-02-12 22:07 UTC, NicoRiri reviewed
Fixed the mentionned issues

2023-02-13 20:10 UTC, MAXOUXAX approved these changes

2023-05-18 22:02 UTC, closed without merging